# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SjCli < Formula
  desc ""
  homepage "https://github.com/splitjoin/sj-cli"
  version "0.1"

  on_macos do
    url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_darwin_all.tar.gz"
    sha256 "a0596127dfe4908503c86ac31fd5a39885b4dcebe0a7bb95460043b328dcf15b"

    def install
      bin.install "sj"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_linux_arm64.tar.gz"
      sha256 "f2a1ec94c9ddf196cc834edd18162ac16df052f3b7721737542730995993f5cf"

      def install
        bin.install "sj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_linux_amd64.tar.gz"
      sha256 "4f2768c36b2e7a37344cda0fcaee53085908cc66c2f6e6413e4b999ff0f85e44"

      def install
        bin.install "sj"
      end
    end
  end
end
