# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SjCli < Formula
  desc ""
  homepage "https://github.com/splitjoin/sj-cli"
  version "0.1"

  on_macos do
    url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_darwin_all.tar.gz"
    sha256 "cb979fa01039154c95f0bb52d5159f2d600a0a073d9cb37922a191cd9cb90f47"

    def install
      bin.install "sj-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_linux_arm64.tar.gz"
      sha256 "031e43a4e15446dee8fc32deee7fc4b068f992bdafc36edd4442f09b9a440cca"

      def install
        bin.install "sj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_linux_amd64.tar.gz"
      sha256 "e886a1dbac938b6f4bddbe120ce1a8384a85fe5ac57fb9b407cd13c4595077a2"

      def install
        bin.install "sj"
      end
    end
  end
end
