# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sj < Formula
  desc ""
  homepage "https://github.com/splitjoin/sj-cli"
  version "0.1"

  on_macos do
    url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_darwin_all.tar.gz"
    sha256 "188cd7cfb2d8c087b4434a43342e096c44e96b1fd107e5c6a8480b1aae7abb09"

    def install
      bin.install "sj"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_linux_arm64.tar.gz"
      sha256 "221502841e5e270da85b76028c4808385809c3a6360c01300bf374e375d8234c"

      def install
        bin.install "sj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/splitjoin/sj-cli/releases/download/v0.1/sj-cli_0.1_linux_amd64.tar.gz"
      sha256 "c0b80029657dd600016ae533620167ab13fc392d0f40d7f6e3d262a62a7a9054"

      def install
        bin.install "sj"
      end
    end
  end
end
